services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: cache_me_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: backend/
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/cache_me_db
    env_file:
      - backend/.env
    depends_on:
      - db

volumes:
  pgdata:
